baseurl: '/'
permalink: pretty
title: 'CoE-QT @ DBATU'

logo:
  mobile: "images/logo/dbatulogo.jpg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/coe-qt.svg"
  desktop_height: "64px"
  desktop_width: "240px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  events:
    output: true
    sort_by: weight
  classes:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "classes"
    values:
      layout: "class"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
